jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This fixes the 'Permission denied' error
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install Requests
        run: pip install requests
      - name: Run Upload
        env:
          ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
          ROBLOX_GROUP_ID: ${{ secrets.ROBLOX_GROUP_ID }}
        run: python upload_audio.py
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add Ids
          git commit -m "Added new music IDs" || exit 0
          git push
